(() => {
  'use strict';
  const D=window.SST_STORY, R=window.SSTRuby; document.title=R.plain(D.meta.title||'B5 SST Player');
  const $=id=>document.getElementById(id);
  const ids=['app','bgA','bgB','modeBadge','phaseLabel','chapterDots','b5Compass','readBtn','motionBtn','soundBtn','startPanel','storyTitle','storySubtitle','storyGoal','startBtn','goalPanel','goalTitle','goalText','goalBenefit','goalFuture','goalPrimaryBlock','goalSupportBlock','goalPageIndicator','goalNext','dialoguePanel','speaker','dialogueText','tapHint','situationPanel','situationTitle','situationGrid','situationFeedback','situationNext','wantPanel','wantTitle','wantGrid','choicePanel','choiceCoach','choiceTitle','choiceGrid','reactionPanel','pickedText','reactionText','reactionNext','observePanel','observeGrid','observeFeedback','observeNext','reflectPanel','wantSummary','impactSummary','specificFeedback','reflectCompareBlock','reflectFeedbackBlock','reflectPageIndicator','reflectNext','repairChoicePanel','repairChoiceGrid','repairPanel','repairPicked','repairReaction','repairNext','modelPanel','modelTitle','modelImage','modelDialogue','modelSteps','modelExamples','modelSceneBlock','modelStepsBlock','modelExamplesBlock','modelPageIndicator','retryBtn','reviewPanel','reviewSkills','reviewStart','generalizePanel','reviewProgress','generalizeTitle','generalizeIntro','generalizeGrid','generalizeReactionPanel','generalizePicked','generalizeReaction','generalizeFeedback','generalizeNext','transitionPanel','transitionKicker','transitionSpeaker','transitionText','transitionHint','endingPanel','endingSkills','endingFutureSummary','endingRecapBlock','endingFutureBlock','endingMissionBlock','endingPageIndicator','endingNext','missionGrid','missionSave','adultBtn','adultRecord','savedPanel','savedMission','finishBtn','returnPanel','returnMission','returnGrid','skipReturn','returnReflectPanel','returnQuestion','returnReflectGrid','returnNext','storyVersionMini','playerVersionRuntime','storyEpisodeLabel','storyEpisodeKicker','storyRoute','reviewHeading'];
  const el=Object.fromEntries(ids.map(id=>[id,$(id)]));
  const STORY_KEY=(D.meta&&D.meta.storyId)||'story'; const STORAGE={pending:`b5_sst_pending_${STORY_KEY}`,history:`b5_sst_history_${STORY_KEY}`};
  const sections=['startPanel','goalPanel','dialoguePanel','situationPanel','wantPanel','choicePanel','reactionPanel','observePanel','reflectPanel','repairChoicePanel','repairPanel','modelPanel','reviewPanel','generalizePanel','generalizeReactionPanel','transitionPanel','endingPanel','savedPanel','returnPanel','returnReflectPanel'];
  const state={moduleIndex:0,reviewIndex:0,inReview:false,introIndex:0,transitionIndex:0,transitionLine:0,goalPage:0,reflectPage:0,modelPage:0,endingPage:0,phase:'start',bg:'A',typing:false,timer:null,typeTarget:null,fullText:'',reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,sound:true,readCount:0,want:null,mode:'probe',currentChoice:null,currentRepair:null,currentGeneralize:null,situationAttempts:0,observeAttempts:0,seenRehearsal:new Set(),seenGeneralize:new Set(),selectedMission:null,pending:null,reflectionStep:0,reflectionAnswers:{},reflectionOutcome:null,records:[]};

  const safeLoad=(k,f=null)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(_){return f}};
  const safeSave=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}};
  const safeRemove=k=>{try{localStorage.removeItem(k)}catch(_){}};
  function addHistory(x){const h=safeLoad(STORAGE.history,[])||[];h.push(x);while(h.length>60)h.shift();safeSave(STORAGE.history,h)}
  function freshRecords(){return D.modules.map(m=>({id:m.id,situationAttempts:0,want:null,probe:null,observeAttempts:0,repairAttempts:[],repairSuccess:false,rehearsalAttempts:[],rehearsalFinal:null,generalizeAttempts:[],generalizeFinal:null,generalizeSuccess:false}))}
  state.records=freshRecords();

  function hideAll(){sections.forEach(id=>el[id]?.classList.add('hidden'))}
  function currentModule(){return D.modules[state.moduleIndex]}
  function currentRecord(){return state.records[state.moduleIndex]}
  function setText(target,text){R.set(target,text)}
  const SAFE_HEX=/^#[0-9a-fA-F]{6}$/;
  function normalizeLine(raw,fallbackSpeaker=''){
    if(raw&&typeof raw==='object'&&!Array.isArray(raw))return {speaker:raw.speaker??fallbackSpeaker,text:raw.text??'',kind:raw.kind||'',textColor:raw.textColor||'',background:raw.background||''};
    return {speaker:fallbackSpeaker,text:String(raw??''),kind:fallbackSpeaker==='ナレーション'?'narration':'',textColor:'',background:''};
  }
  function storyLineKind(line){
    if(['narration','dialogue','thought'].includes(line.kind))return line.kind;
    const speaker=R.plain(line.speaker||'').trim();
    if(speaker==='ナレーション')return 'narration';
    if(String(line.text||'').trim().startsWith('（'))return 'thought';
    return 'dialogue';
  }
  function applyStoryLineStyle(panel,speakerEl,raw,fallbackSpeaker=''){
    const line=normalizeLine(raw,fallbackSpeaker),kind=storyLineKind(line);
    panel.classList.remove('story-line--narration','story-line--dialogue','story-line--thought');
    panel.classList.add(`story-line--${kind}`);
    panel.dataset.lineKind=kind;
    panel.style.removeProperty('--story-line-text');panel.style.removeProperty('--story-line-bg');
    const hints=D.meta?.displayHints?.[kind]||{};
    const color=SAFE_HEX.test(line.textColor)?line.textColor:(SAFE_HEX.test(hints.textColor||'')?hints.textColor:'');
    const bg=SAFE_HEX.test(line.background)?line.background:(SAFE_HEX.test(hints.background||'')?hints.background:'');
    if(color)panel.style.setProperty('--story-line-text',color);
    if(bg)panel.style.setProperty('--story-line-bg',bg);
    setText(speakerEl,line.speaker||fallbackSpeaker||(kind==='narration'?'ナレーション':''));
    return line;
  }
  function setUIMode(mode){
    el.app.dataset.uiMode=mode;
    const map={story:['ものがたり','story'],coach:['SSTコーチ','coach'],review:['ふりかえり','review'],real:['げんじつへ','real']};
    const v=map[mode]||map.coach;
    el.modeBadge.textContent=v[0];el.modeBadge.className=`mode-badge ${v[1]}`;
  }
  function setPhase(label,b5='look'){
    state.phase=label;R.set(el.phaseLabel,label);
    const order=['look','want','tell','other'], ai=order.indexOf(b5);
    [...el.b5Compass.querySelectorAll('[data-b5]')].forEach((s,i)=>{s.classList.toggle('active',s.dataset.b5===b5);s.classList.toggle('done',i<ai)});
  }
  function updateChapters(){
    el.chapterDots.innerHTML='';
    const bridge=state.phase==='[[物語|ものがたり]]のつなぎ';
    D.modules.forEach((m,i)=>{const x=document.createElement('span');x.textContent=String(i+1);x.title=R.plain(m.short);if(state.inReview||i<state.moduleIndex||(bridge&&i===state.moduleIndex))x.classList.add('done');if(!state.inReview&&i===state.moduleIndex&&!bridge)x.classList.add('active');el.chapterDots.appendChild(x)});
  }
  function setBg(src,focus='center'){
    const incoming=state.bg==='A'?el.bgB:el.bgA, outgoing=state.bg==='A'?el.bgA:el.bgB;
    incoming.style.backgroundImage=`url("${src}")`;incoming.style.backgroundPosition=focus;incoming.style.transformOrigin=focus;incoming.classList.add('active');outgoing.classList.remove('active');state.bg=state.bg==='A'?'B':'A';
  }
  function beep(kind='tap'){
    if(!state.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext,ctx=beep.ctx||(beep.ctx=new AC()),o=ctx.createOscillator(),g=ctx.createGain(),n=ctx.currentTime;const c={tap:[480,.04,.02],good:[660,.11,.035],think:[310,.09,.02],next:[540,.07,.025]}[kind]||[480,.04,.02];o.type=kind==='think'?'triangle':'sine';o.frequency.value=c[0];g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(c[2],n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+c[1]);o.connect(g);g.connect(ctx.destination);o.start(n);o.stop(n+c[1]+.02)}catch(_){}}

  function stopTyping(){clearTimeout(state.timer);state.typing=false;state.typeTarget=null}
  function richTokens(text){const out=[],re=/\[\[([^|\]]+)\|([^\]]+)\]\]/g;let last=0,m;while((m=re.exec(text))){for(const ch of Array.from(text.slice(last,m.index)))out.push(ch);out.push(m[0]);last=re.lastIndex}for(const ch of Array.from(text.slice(last)))out.push(ch);return out}
  function typeText(target,text,onDone){stopTyping();target.innerHTML='';state.typing=true;state.typeTarget=target;state.fullText=text;const toks=richTokens(text);if(state.reduced){R.set(target,text);stopTyping();onDone?.();return}let i=0;const tick=()=>{if(!state.typing||state.typeTarget!==target)return;const tok=toks[i++];target.insertAdjacentHTML('beforeend',R.html(tok));if(i<toks.length)state.timer=setTimeout(tick,/[、。！？…\n]/.test(R.plain(tok))?60:24);else{stopTyping();onDone?.()}};tick()}
  function finishTyping(){if(!state.typing||!state.typeTarget)return false;const t=state.typeTarget,x=state.fullText;stopTyping();R.set(t,x);return true}
  function renderButtons(container,items,onPick,seen=null){container.innerHTML='';items.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.className='choice';const label=typeof item==='string'?item:item.label,key=typeof item==='string'?R.plain(label):(item.id||R.plain(label));b.innerHTML=`<span class="num">${i+1}</span><span>${R.html(label)}</span>`;if(seen?.has(key))b.classList.add('seen');b.addEventListener('click',()=>{beep('tap');onPick(item,i,b)});container.appendChild(b)})}
  function selectBtn(container,b){[...container.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}
  function showBlock(node,show){if(node)node.classList.toggle('hidden',!show)}
  function setPageIndicator(node,current,total){if(node)setText(node,`1つずつ / ${current} / ${total}`)}


  function visibleSection(){return sections.map(id=>el[id]).find(x=>x&&!x.classList.contains('hidden'))}
  function stopSpeech(){try{speechSynthesis.cancel()}catch(_){}}
  function readVisible(){if(!('speechSynthesis' in window))return;if(finishTyping()){}stopSpeech();const sec=visibleSection();if(!sec)return;const c=sec.cloneNode(true);c.querySelectorAll('.hidden').forEach(x=>x.remove());c.querySelectorAll('rt').forEach(rt=>{const rb=rt.parentElement;if(rb&&rb.tagName==='RUBY')rb.replaceWith(document.createTextNode(rt.textContent))});c.querySelectorAll('.num').forEach(n=>n.textContent=`${n.textContent}ばん`);const t=c.innerText.replace(/\s+/g,' ').trim();if(!t)return;const u=new SpeechSynthesisUtterance(t);u.lang='ja-JP';u.rate=.92;state.readCount++;speechSynthesis.speak(u)}

  function setupStoryChrome(){const m=String(D.meta.storyId||'').match(/(\d+)$/);const no=m?String(Number(m[1])):'';const episode=no?`[[第|だい]]${no}[[話|わ]]`:'[[物語|ものがたり]]';setText(el.storyEpisodeLabel,episode);setText(el.storyEpisodeKicker,episode);if(el.storyRoute)el.storyRoute.classList.toggle('hidden',D.meta.storyId!=='story-001');if(el.reviewHeading)setText(el.reviewHeading,'[[物語|ものがたり]]を[[最後|さいご]]まで[[見|み]]ました')}

  function showStart(){hideAll();delete el.app.dataset.tone;el.app.classList.remove('transition-mode');state.inReview=false;state.reviewIndex=0;state.moduleIndex=0;setUIMode('story');setPhase('はじめに','look');updateChapters();setBg(D.meta.coverImage||D.modules[0].introImage,'54% 50%');setText(el.storyTitle,D.meta.title);setText(el.storySubtitle,D.meta.subtitle);setText(el.storyGoal,D.meta.storyGoal);el.startPanel.classList.remove('hidden')}
  function startStory(){state.records=freshRecords();state.moduleIndex=0;state.reviewIndex=0;state.inReview=false;startModule()}
  function startModule(){setUIMode('coach');const m=currentModule();state.introIndex=0;state.want=null;state.mode='probe';state.currentChoice=null;state.currentRepair=null;state.currentGeneralize=null;state.situationAttempts=0;state.observeAttempts=0;state.seenRehearsal=new Set();state.seenGeneralize=new Set();el.app.classList.remove('transition-mode');updateChapters();showGoal()}
  function showGoal(){hideAll();setUIMode('coach');delete el.app.dataset.tone;const m=currentModule();state.goalPage=0;setPhase(`SST ${m.no} / 5　これから学ぶこと`,'look');setBg(m.introImage,m.focus||'center');setText(el.goalTitle,m.title);setText(el.goalText,m.goal);setText(el.goalBenefit,m.benefit);setText(el.goalFuture,`この[[力|ちから]]は、${m.future}`);el.goalPanel.classList.remove('hidden');renderGoalPage()}
  function renderGoalPage(){const first=state.goalPage===0;showBlock(el.goalPrimaryBlock,first);showBlock(el.goalSupportBlock,!first);setPageIndicator(el.goalPageIndicator,state.goalPage+1,2);setText(el.goalNext,first?'なぜ[[大切|たいせつ]]かを[[見|み]]る':'このねらいで[[場面|ばめん]]を[[見|み]]る')}
  function advanceGoal(){if(state.goalPage===0){state.goalPage=1;renderGoalPage();return}showIntroLine()}
  function showIntroLine(){hideAll();setUIMode('story');delete el.app.dataset.tone;const m=currentModule();setPhase(`SST ${m.no} / 5　${m.short}`,'look');setBg(m.introImage,m.focus||'center');el.dialoguePanel.classList.remove('hidden');const line=applyStoryLineStyle(el.dialoguePanel,el.speaker,m.intro[state.introIndex]);setText(el.tapHint,'タップで[[全文|ぜんぶん]]');typeText(el.dialogueText,line.text,()=>setText(el.tapHint,state.introIndex<m.intro.length-1?'タップで[[次|つぎ]]へ':'タップで[[状況|じょうきょう]]をみる'))}
  function advanceIntro(){if(finishTyping()){setText(el.tapHint,state.introIndex<currentModule().intro.length-1?'タップで[[次|つぎ]]へ':'タップで[[状況|じょうきょう]]をみる');return}if(state.introIndex<currentModule().intro.length-1){state.introIndex++;showIntroLine()}else showSituation()}
  function showSituation(){hideAll();setUIMode('coach');const m=currentModule();setPhase(`SST ${m.no} / 5　[[状況|じょうきょう]]をみる`,'look');setBg(m.introImage,m.focus||'center');el.situationPanel.classList.remove('hidden');el.situationFeedback.classList.add('hidden');el.situationNext.classList.add('hidden');setText(el.situationTitle,m.situation.prompt);renderButtons(el.situationGrid,m.situation.options,(item,i,b)=>{state.situationAttempts++;currentRecord().situationAttempts=state.situationAttempts;if(i===m.situation.correct){selectBtn(el.situationGrid,b);setText(el.situationFeedback,'そうだね。まず、[[時間|じかん]]・[[相手|あいて]]・[[周|まわ]]りのようすを[[見|み]]ました。');el.situationFeedback.classList.remove('hidden');el.situationNext.classList.remove('hidden');beep('good')}else{b.classList.add('try-again');setText(el.situationFeedback,'もう[[一度|いちど]]、[[画面|がめん]]の[[人|ひと]]・[[場所|ばしょ]]・[[動|うご]]きを[[見|み]]てみよう。');el.situationFeedback.classList.remove('hidden');beep('think')}})}
  function showWant(){hideAll();setUIMode('coach');const m=currentModule();setPhase(`SST ${m.no} / 5　どうしたい？`,'want');el.wantPanel.classList.remove('hidden');setText(el.wantTitle,m.wantPrompt);renderButtons(el.wantGrid,m.wants,(item,_,b)=>{state.want=item;currentRecord().want=item;selectBtn(el.wantGrid,b);setTimeout(()=>showChoices('probe'),120)})}
  function showChoices(mode){hideAll();setUIMode('coach');state.mode=mode;delete el.app.dataset.tone;const m=currentModule();setPhase(`SST ${m.no} / 5　${mode==='probe'?'まずどうする？':'[[練習|れんしゅう]]'}`,'tell');setBg(m.introImage,m.focus||'center');el.choicePanel.classList.remove('hidden');setText(el.choiceCoach,mode==='probe'?'まずは、[[今|いま]]の[[自分|じぶん]]ならどうするか[[選|えら]]ぶ':'[[見本|みほん]]を[[見|み]]たあと、こんどは[[自分|じぶん]]で[[練習|れんしゅう]]する');setText(el.choiceTitle,mode==='probe'?'ゆうとは、どうする？':'もう[[一度|いちど]]、どうする？');renderButtons(el.choiceGrid,m.choices,c=>choose(c),mode==='rehearsal'?state.seenRehearsal:null)}
  function choose(c){state.currentChoice=c;const r=currentRecord();if(state.mode==='probe')r.probe=c.id;else{r.rehearsalAttempts.push(c.id);state.seenRehearsal.add(c.id)}showReaction(c)}
  function showReaction(c){hideAll();setUIMode('story');const m=currentModule();setPhase(`SST ${m.no} / 5　[[相手|あいて]]をみる`,'other');setBg(c.image);el.app.dataset.tone=c.tone||'neutral';el.reactionPanel.classList.remove('hidden');setText(el.pickedText,`ゆうとの[[選択|せんたく]]：${c.label}`);el.reactionText.innerHTML='';el.reactionNext.classList.add('hidden');setTimeout(()=>typeText(el.reactionText,c.reaction,()=>{const lab=state.mode==='probe'?'つぎへ':(c.accepted?'つぎの[[場面|ばめん]]でためす':'もう[[一度|いちど]][[練習|れんしゅう]]する');setText(el.reactionNext,lab);el.reactionNext.classList.remove('hidden');beep(c.accepted?'good':'think')}),state.reduced?0:480)}
  function afterReaction(){if(finishTyping()){el.reactionNext.classList.remove('hidden');return}if(state.mode==='probe')showObserve();else if(state.currentChoice.accepted){currentRecord().rehearsalFinal=state.currentChoice.id;completeModule()}else showChoices('rehearsal')}
  function showObserve(){hideAll();setUIMode('coach');const c=state.currentChoice,m=currentModule();setPhase(`SST ${m.no} / 5　[[起|お]]きたこと`,'other');el.observePanel.classList.remove('hidden');el.observeFeedback.classList.add('hidden');el.observeNext.classList.add('hidden');renderButtons(el.observeGrid,c.observe,(item,i,b)=>{state.observeAttempts++;currentRecord().observeAttempts=state.observeAttempts;if(i===c.correct){selectBtn(el.observeGrid,b);setText(el.observeFeedback,'そうだね。まずは「[[相手|あいて]]の[[気持|きも]]ち」を[[決|き]]めつけず、[[見|み]]えたことを[[確|たし]]かめました。');el.observeFeedback.classList.remove('hidden');el.observeNext.classList.remove('hidden');beep('good')}else{b.classList.add('try-again');setText(el.observeFeedback,'もう[[一度|いちど]]、[[身体|からだ]]の[[向|む]]き・[[距離|きょり]]・[[動|うご]]きを[[見|み]]よう。');el.observeFeedback.classList.remove('hidden');beep('think')}})}
  function showReflect(){hideAll();setUIMode('coach');const c=state.currentChoice,m=currentModule();state.reflectPage=0;setPhase(`SST ${m.no} / 5　[[振|ふ]]り[[返|かえ]]る`,'other');el.reflectPanel.classList.remove('hidden');setText(el.wantSummary,state.want||'まだよく[[分|わ]]からない');setText(el.impactSummary,c.impact);setText(el.specificFeedback,c.feedback);renderReflectPage()}
  function renderReflectPage(){const first=state.reflectPage===0;showBlock(el.reflectCompareBlock,first);showBlock(el.reflectFeedbackBlock,!first);setPageIndicator(el.reflectPageIndicator,state.reflectPage+1,2);if(first)setText(el.reflectNext,'ポイントを[[見|み]]る');else setText(el.reflectNext,state.currentChoice.accepted?'[[見本|みほん]]を[[見|み]]る':'[[言|い]]い[[直|なお]]し・[[修復|しゅうふく]]を[[練習|れんしゅう]]する')}
  function advanceReflectPage(){if(state.reflectPage===0){state.reflectPage=1;renderReflectPage();return}afterReflect()}
  function afterReflect(){if(state.currentChoice.accepted)showModel();else showRepairChoices()}
  function showRepairChoices(){hideAll();setUIMode('coach');const m=currentModule();setPhase(`SST ${m.no} / 5　[[立|た]]て[[直|なお]]す`,'tell');setBg(state.currentChoice.image);el.repairChoicePanel.classList.remove('hidden');renderButtons(el.repairChoiceGrid,m.repairChoices,(r,_,b)=>{state.currentRepair=r;currentRecord().repairAttempts.push(R.plain(r.label));selectBtn(el.repairChoiceGrid,b);setTimeout(()=>showRepairResult(r),120)})}
  function showRepairResult(r){hideAll();setUIMode('story');const m=currentModule();setPhase(`SST ${m.no} / 5　[[立|た]]て[[直|なお]]したあと`,'other');setBg(r.accepted?m.model.image:state.currentChoice.image);el.app.dataset.tone=r.accepted?'neutral':'pressing';el.repairPanel.classList.remove('hidden');setText(el.repairPicked,`ゆうと：${r.label}`);el.repairReaction.innerHTML='';el.repairNext.classList.add('hidden');setTimeout(()=>typeText(el.repairReaction,r.response,()=>{setText(el.repairNext,r.accepted?'[[見本|みほん]]を[[見|み]]る':'もう[[一度|いちど]][[言|い]]い[[直|なお]]す');el.repairNext.classList.remove('hidden');beep(r.accepted?'good':'think')}),state.reduced?0:380)}
  function afterRepair(){if(finishTyping()){el.repairNext.classList.remove('hidden');return}if(state.currentRepair?.accepted){currentRecord().repairSuccess=true;showModel()}else showRepairChoices()}
  function showModel(){hideAll();setUIMode('coach');const m=currentModule();state.modelPage=0;delete el.app.dataset.tone;setPhase(`SST ${m.no} / 5　[[見本|みほん]]`,'tell');setBg(m.model.image,m.focus||'center');el.modelPanel.classList.remove('hidden');setText(el.modelTitle,m.modelTitle);el.modelImage.src=m.model.image;el.modelImage.alt=R.plain(`${m.title}の[[見本|みほん]]`);el.modelDialogue.innerHTML='';m.model.lines.forEach(raw=>{const line=normalizeLine(raw),kind=storyLineKind(line),d=document.createElement('div');d.className=`model-line model-line--${kind}`;d.innerHTML=`<span class="who">${R.html(line.speaker)}</span><div class="say">${R.html(line.text)}</div>`;el.modelDialogue.appendChild(d)});el.modelSteps.innerHTML='';m.modelSteps.forEach((s,i)=>{const d=document.createElement('div');d.innerHTML=`<b>${i+1}</b><span>${R.html(s)}</span>`;el.modelSteps.appendChild(d)});el.modelExamples.innerHTML=m.modelExamples.map(x=>`<div>${R.html(x)}</div>`).join('');renderModelPage()}
  function renderModelPage(){const stepItems=[...el.modelSteps.children],stepPages=Math.max(1,Math.ceil(stepItems.length/2)),examplePage=stepPages+1,total=stepPages+2;showBlock(el.modelSceneBlock,state.modelPage===0);showBlock(el.modelStepsBlock,state.modelPage>=1&&state.modelPage<=stepPages);showBlock(el.modelExamplesBlock,state.modelPage===examplePage);stepItems.forEach((node,i)=>{const page=Math.floor(i/2)+1;node.classList.toggle('hidden',state.modelPage!==page)});setPageIndicator(el.modelPageIndicator,state.modelPage+1,total);if(state.modelPage===0)setText(el.retryBtn,'ポイントを[[見|み]]る');else if(state.modelPage<stepPages)setText(el.retryBtn,'つぎのポイントを[[見|み]]る');else if(state.modelPage===stepPages)setText(el.retryBtn,'[[言|い]]い[[方|かた]]の[[例|れい]]を[[見|み]]る');else setText(el.retryBtn,'こんどは[[自分|じぶん]]で[[練習|れんしゅう]]する')}
  function advanceModelPage(){const stepPages=Math.max(1,Math.ceil(el.modelSteps.children.length/2)),lastPage=stepPages+1;if(state.modelPage<lastPage){state.modelPage++;renderModelPage();return}showChoices('rehearsal')}
  function showReviewIntro(){
    hideAll();delete el.app.dataset.tone;el.app.classList.remove('transition-mode');state.inReview=true;state.reviewIndex=0;setUIMode('review');setPhase('[[一日|いちにち]]の[[振|ふ]]り[[返|かえ]]り','other');setBg(D.meta.endingImage||D.modules[D.modules.length-1].introImage,'55% 50%');updateChapters();el.reviewPanel.classList.remove('hidden');el.reviewSkills.innerHTML=''
  }
  function showGeneralize(){
    hideAll();delete el.app.dataset.tone;state.inReview=true;setUIMode('review');const m=D.modules[state.reviewIndex],g=m.generalize;setPhase(`[[確認|かくにん]] ${state.reviewIndex+1} / 5`,'look');updateChapters();setBg(g.image,g.focus||'center');el.generalizePanel.classList.remove('hidden');setText(el.reviewProgress,`[[振|ふ]]り[[返|かえ]]り・[[確認|かくにん]] ${state.reviewIndex+1} / 5`);setText(el.generalizeIntro,g.intro);state.currentGeneralize=null;state.seenGeneralize=new Set();renderButtons(el.generalizeGrid,g.choices,(c,_,b)=>{state.currentGeneralize=c;state.records[state.reviewIndex].generalizeAttempts.push(R.plain(c.label));state.seenGeneralize.add(R.plain(c.label));selectBtn(el.generalizeGrid,b);setTimeout(()=>showGeneralizeReaction(c),120)},state.seenGeneralize)
  }
  function showGeneralizeReaction(c){
    hideAll();setUIMode('review');setBg(c.resultImage);el.app.dataset.tone=c.accepted?'neutral':'pressing';el.generalizeReactionPanel.classList.remove('hidden');setText(el.generalizePicked,`ゆうとの[[選択|せんたく]]：${c.label}`);el.generalizeReaction.innerHTML='';el.generalizeFeedback.innerHTML='';el.generalizeNext.classList.add('hidden');setTimeout(()=>typeText(el.generalizeReaction,c.reaction,()=>{setText(el.generalizeFeedback,c.feedback);const last=state.reviewIndex===D.modules.length-1;setText(el.generalizeNext,c.accepted?(last?'[[確認|かくにん]]を[[終|お]]える':'つぎの[[確認|かくにん]]へ'):'もう[[一度|いちど]][[考|かんが]]える');el.generalizeNext.classList.remove('hidden');beep(c.accepted?'good':'think')}),state.reduced?0:400)
  }
  function afterGeneralize(){
    if(finishTyping()){el.generalizeNext.classList.remove('hidden');return}
    if(state.currentGeneralize.accepted){const r=state.records[state.reviewIndex];r.generalizeFinal=R.plain(state.currentGeneralize.label);r.generalizeSuccess=true;if(state.reviewIndex<D.modules.length-1){state.reviewIndex++;showGeneralize()}else showEnding()}else showGeneralize()
  }
  function completeModule(){if(state.moduleIndex<D.modules.length-1)showTransition(state.moduleIndex);else showReviewIntro()}
  function showTransition(idx){hideAll();setUIMode('story');delete el.app.dataset.tone;el.app.classList.add('transition-mode');state.transitionIndex=idx;state.transitionLine=0;const t=D.transitions[idx];setPhase('[[物語|ものがたり]]のつなぎ','look');updateChapters();setBg(t.image,t.focus||'center');el.transitionPanel.classList.remove('hidden');setText(el.transitionKicker,t.kicker);showTransitionLine()}
  function showTransitionLine(){const t=D.transitions[state.transitionIndex];const line=applyStoryLineStyle(el.transitionPanel,el.transitionSpeaker,t.lines[state.transitionLine],'ナレーション');setText(el.transitionHint,'タップで[[全文|ぜんぶん]]');typeText(el.transitionText,line.text,()=>setText(el.transitionHint,state.transitionLine<t.lines.length-1?'タップで[[次|つぎ]]へ':'タップで[[次|つぎ]]のSSTへ'))}
  function advanceTransition(){if(finishTyping()){const t=D.transitions[state.transitionIndex];setText(el.transitionHint,state.transitionLine<t.lines.length-1?'タップで[[次|つぎ]]へ':'タップで[[次|つぎ]]のSSTへ');return}const t=D.transitions[state.transitionIndex];if(state.transitionLine<t.lines.length-1){state.transitionLine++;showTransitionLine()}else{state.moduleIndex++;startModule()}}

  function showEnding(){hideAll();setUIMode('real');delete el.app.dataset.tone;el.app.classList.remove('transition-mode');state.endingPage=0;setPhase('[[確認編|かくにんへん]] おわり','other');setBg(D.meta.endingImage||D.modules[D.modules.length-1].introImage,'55% 50%');updateChapters();[...el.chapterDots.children].forEach(s=>{s.classList.remove('active');s.classList.add('done')});el.endingPanel.classList.remove('hidden');if(el.endingFutureSummary)setText(el.endingFutureSummary,D.meta.futureSummary||'[[今日|きょう]]の5つは、[[大人|おとな]]になって[[働|はたら]]くときにも[[使|つか]]う[[力|ちから]]につながります。');state.selectedMission=null;el.missionSave.classList.add('hidden');renderButtons(el.missionGrid,D.missions,(m,_,b)=>{state.selectedMission=m;selectBtn(el.missionGrid,b);el.missionSave.classList.remove('hidden')});renderAdult();renderEndingPage()}
  function renderEndingPage(){const recapPages=Math.ceil(D.modules.length/2),futurePage=recapPages,missionPage=recapPages+1,total=recapPages+2;showBlock(el.endingRecapBlock,state.endingPage<recapPages);showBlock(el.endingFutureBlock,state.endingPage===futurePage);showBlock(el.endingMissionBlock,state.endingPage===missionPage);if(state.endingPage<recapPages){const from=state.endingPage*2,to=Math.min(from+2,D.modules.length);el.endingSkills.innerHTML=D.modules.slice(from,to).map(m=>`<div><b>SST ${m.no}</b><span>${R.html(m.short)}</span></div>`).join('')}setPageIndicator(el.endingPageIndicator,state.endingPage+1,total);if(state.endingPage<missionPage){setText(el.endingNext,state.endingPage<recapPages-1?'つぎの2つを[[見|み]]る':state.endingPage===recapPages-1?'[[将来|しょうらい]]につながる[[力|ちから]]を[[見|み]]る':'[[今日|きょう]]のミッションを[[選|えら]]ぶ');el.endingNext.classList.remove('hidden')}else el.endingNext.classList.add('hidden')}
  function advanceEndingPage(){const missionPage=Math.ceil(D.modules.length/2)+1;if(state.endingPage<missionPage){state.endingPage++;renderEndingPage()}}

  function label(m,id){return m.choices.find(c=>c.id===id)?.label||'—'}
  function renderAdult(){const rows=D.modules.map((m,i)=>{const r=state.records[i];return `<tr><th>SST ${m.no}<br>${R.html(m.short)}</th><td>${R.html('[[状況|じょうきょう]][[確認|かくにん]]')}：${r.situationAttempts} ${R.html('[[回|かい]]')}<br>${R.html('[[初回|しょかい]]')}：${R.html(label(m,r.probe))}<br>${R.html('[[観察|かんさつ]][[試行|しこう]]')}：${r.observeAttempts} ${R.html('[[回|かい]]')}<br>${R.html('[[修復|しゅうふく]]')}：${r.repairSuccess?R.html('[[成立|せいりつ]]'):R.html('[[不要|ふよう]]または[[未成立|みせいりつ]]')}<br>${R.html('[[再練習|さいれんしゅう]]')}：${R.html(label(m,r.rehearsalFinal))}<br>${R.html('[[般化|はんか]]')}：${r.generalizeSuccess?R.html('[[成立|せいりつ]]'):R.html('[[未成立|みせいりつ]]')}</td></tr>`}).join('');el.adultRecord.innerHTML=`<table>${rows}<tr><th>${R.html('[[読|よ]]み[[上|あ]]げ')}</th><td>${state.readCount} ${R.html('[[回|かい]]')}</td></tr></table><p>${R.html('※ [[点数|てんすう]]ではなく、[[状況理解|じょうきょうりかい]]・[[初回|しょかい]]・[[相手|あいて]]の[[反応|はんのう]]の[[観察|かんさつ]]・[[修復|しゅうふく]]・[[再練習|さいれんしゅう]]・[[般化|はんか]]を[[見|み]]ます。')}</p>`}
  function saveMission(){if(!state.selectedMission)return;setUIMode('real');const rec={id:state.selectedMission.id,label:state.selectedMission.label,skill:state.selectedMission.skill,createdAt:new Date().toISOString()};safeSave(STORAGE.pending,rec);state.pending=rec;hideAll();setPhase('[[現実|げんじつ]]ミッション','tell');el.savedPanel.classList.remove('hidden');setText(el.savedMission,rec.label)}

  const outcomes=[{id:'tried',label:'やってみた'},{id:'hard',label:'やってみたけど、うまくいかなかった'},{id:'none',label:'その[[場面|ばめん]]がなかった'}];
  function showReturn(rec){hideAll();setUIMode('real');setBg(D.meta.coverImage||D.modules[0].introImage,'54% 50%');setPhase('[[前回|ぜんかい]]のつづき','look');el.returnPanel.classList.remove('hidden');setText(el.returnMission,rec.label);renderButtons(el.returnGrid,outcomes,o=>handleOutcome(o.id))}
  function handleOutcome(id){state.reflectionOutcome=id;if(id==='none'){addHistory({mission:state.pending,outcome:id,at:new Date().toISOString()});hideAll();el.returnReflectPanel.classList.remove('hidden');setPhase('[[現実|げんじつ]]の[[振|ふ]]り[[返|かえ]]り','other');setText(el.returnQuestion,'その[[場面|ばめん]]がなかったなら、まだ「できなかった」ではありません。ミッションはそのままにしておきます。');el.returnReflectGrid.innerHTML='';el.returnNext.classList.remove('hidden');setText(el.returnNext,'[[今日|きょう]]の[[物語|ものがたり]]へ');el.returnNext.onclick=()=>showStart();return}state.reflectionStep=0;state.reflectionAnswers={};showReturnStep()}
  const reflection=[{q:'そのとき、[[自分|じぶん]]はどうした？',key:'self',choices:['[[言葉|ことば]]で[[伝|つた]]えた','うなずきや[[動作|どうさ]]で[[伝|つた]]えた','[[言|い]]い[[直|なお]]した','うまく[[伝|つた]]えられなかった','よく[[覚|おぼ]]えていない']},{q:'そのあと、[[相手|あいて]]はどうした？',key:'other',choices:['[[分|わ]]かったようすだった','[[強|つよ]]い[[言|い]]い[[方|かた]]で[[返|かえ]]された','もう[[一度|いちど]][[聞|き]]かれた','[[離|はな]]れた・[[話|はなし]]が[[終|お]]わった','よく[[分|わ]]からない']},{q:'つぎに[[似|に]]た[[場面|ばめん]]がきたら？',key:'next',choices:['[[同|おな]]じやり[[方|かた]]を[[使|つか]]う','もっと[[短|みじか]]く[[伝|つた]]える','[[言|い]]い[[直|なお]]す','[[別|べつ]]のやり[[方|かた]]を[[試|ため]]す','まだ[[分|わ]]からない']}];
  function showReturnStep(){hideAll();setUIMode('real');setPhase('[[現実|げんじつ]]の[[振|ふ]]り[[返|かえ]]り','other');el.returnReflectPanel.classList.remove('hidden');el.returnNext.classList.add('hidden');const st=reflection[state.reflectionStep];setText(el.returnQuestion,st.q);renderButtons(el.returnReflectGrid,st.choices,(x,_,b)=>{state.reflectionAnswers[st.key]=x;selectBtn(el.returnReflectGrid,b);el.returnNext.classList.remove('hidden');setText(el.returnNext,state.reflectionStep<reflection.length-1?'[[次|つぎ]]へ':'[[振|ふ]]り[[返|かえ]]りを[[終|お]]える')});el.returnNext.onclick=advanceReturn}
  function advanceReturn(){if(state.reflectionStep<reflection.length-1){state.reflectionStep++;showReturnStep();return}addHistory({mission:state.pending,outcome:state.reflectionOutcome,answers:state.reflectionAnswers,at:new Date().toISOString()});safeRemove(STORAGE.pending);state.pending=null;showStart()}

  el.startBtn.addEventListener('click',()=>{beep('next');startStory()});el.goalNext.addEventListener('click',advanceGoal);el.dialoguePanel.addEventListener('click',advanceIntro);el.dialoguePanel.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();advanceIntro()}});el.situationNext.addEventListener('click',showWant);
  el.reactionPanel.addEventListener('click',e=>{if(e.target===el.reactionNext||el.reactionNext.contains(e.target))return;if(finishTyping())el.reactionNext.classList.remove('hidden')});el.reactionNext.addEventListener('click',afterReaction);el.observeNext.addEventListener('click',showReflect);el.reflectNext.addEventListener('click',advanceReflectPage);el.repairPanel.addEventListener('click',e=>{if(e.target===el.repairNext||el.repairNext.contains(e.target))return;if(finishTyping())el.repairNext.classList.remove('hidden')});el.repairNext.addEventListener('click',afterRepair);el.retryBtn.addEventListener('click',advanceModelPage);el.reviewStart.addEventListener('click',showGeneralize);el.generalizeReactionPanel.addEventListener('click',e=>{if(e.target===el.generalizeNext||el.generalizeNext.contains(e.target))return;if(finishTyping())el.generalizeNext.classList.remove('hidden')});el.generalizeNext.addEventListener('click',afterGeneralize);el.transitionPanel.addEventListener('click',advanceTransition);el.transitionPanel.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();advanceTransition()}});
  el.endingNext.addEventListener('click',advanceEndingPage);el.missionSave.addEventListener('click',saveMission);el.adultBtn.addEventListener('click',()=>{renderAdult();el.adultRecord.classList.toggle('hidden')});el.finishBtn.addEventListener('click',showStart);el.skipReturn.addEventListener('click',showStart);el.readBtn.addEventListener('click',readVisible);el.motionBtn.addEventListener('click',()=>{state.reduced=!state.reduced;el.app.classList.toggle('reduced',state.reduced);el.motionBtn.innerHTML=state.reduced?R.html('[[演出|えんしゅつ]]：[[少|すく]]なめ'):R.html('[[演出|えんしゅつ]]：[[標準|ひょうじゅん]]')});el.soundBtn.addEventListener('click',()=>{state.sound=!state.sound;el.soundBtn.innerHTML=state.sound?R.html('[[効果音|こうかおん]]：あり'):R.html('[[効果音|こうかおん]]：なし')});

  const images=new Set();D.modules.forEach(m=>{images.add(m.introImage);m.choices.forEach(c=>images.add(c.image));images.add(m.model.image);images.add(m.generalize.image);m.generalize.choices.forEach(c=>images.add(c.resultImage))});D.transitions.forEach(t=>images.add(t.image));images.forEach(src=>{const im=new Image();im.src=src});
  el.app.dataset.density='focus';setUIMode('story');setupStoryChrome();if(el.playerVersionRuntime)el.playerVersionRuntime.textContent=`Player v${window.B5_PLAYER_VERSION||'unknown'}`;if(el.storyVersionMini)el.storyVersionMini.textContent=`Story v${D.meta.version||'--'}`;if(!('speechSynthesis' in window))el.readBtn.disabled=true;if(state.reduced)el.app.classList.add('reduced');R.staticMarkers(document.body);setText(el.storyTitle,D.meta.title);setText(el.storySubtitle,D.meta.subtitle);setText(el.storyGoal,D.meta.storyGoal);setBg(D.meta.coverImage||D.modules[0].introImage,'54% 50%');state.pending=safeLoad(STORAGE.pending,null);if(state.pending)showReturn(state.pending);else showStart();
})();
