(() => {
'use strict';
const DB_NAME='b5-sst-player'; const DB_VERSION=1; const STORE='stories';
const ALLOWED_EXT=new Set(['json','webp','png','jpg','jpeg','avif','mp3','ogg','wav','m4a']);
const MAX_PACKAGE=250*1024*1024, MAX_UNPACKED=500*1024*1024, MAX_FILES=500;
const marker=/\[\[[^\]|]+\|[^\]]+\]\]/g, han=/[\u3400-\u4dbf\u4e00-\u9fff]/;
const ignoredTextKeys=new Set(['id','image','introImage','resultImage','focus','tone','version','storyId','format','schemaVersion','guardrailVersion','coverImage','endingImage']);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'storyId'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function tx(mode,fn){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);let req;try{req=fn(s)}catch(e){db.close();reject(e);return}t.oncomplete=()=>{db.close();resolve(req?.result)};t.onerror=()=>{db.close();reject(t.error)};t.onabort=()=>{db.close();reject(t.error)}})}
const list=()=>tx('readonly',s=>s.getAll()); const get=id=>tx('readonly',s=>s.get(id)); const remove=id=>tx('readwrite',s=>s.delete(id)); const put=x=>tx('readwrite',s=>s.put(x));
function cleanPath(p){if(!p||p.startsWith('/')||p.includes('\\')||p.split('/').some(x=>x==='..'||x===''))throw new Error(`不正なファイル名です: ${p}`);return p}
function walkText(x,path='',key=''){const errs=[];if(Array.isArray(x))x.forEach((v,i)=>errs.push(...walkText(v,`${path}[${i}]`,key)));else if(x&&typeof x==='object')Object.entries(x).forEach(([k,v])=>errs.push(...walkText(v,path?`${path}.${k}`:k,k)));else if(typeof x==='string'&&!ignoredTextKeys.has(key)&&!x.startsWith('assets/')){const stripped=x.replace(marker,'');if(han.test(stripped))errs.push(`${path}: ルビのない漢字「${stripped.match(han)[0]}」`)}return errs}
function refs(x,out=new Set()){if(Array.isArray(x))x.forEach(v=>refs(v,out));else if(x&&typeof x==='object')Object.values(x).forEach(v=>refs(v,out));else if(typeof x==='string'&&x.startsWith('assets/'))out.add(x);return out}
function validateStory(story,files){const e=[];if(!story||typeof story!=='object')return ['story.json が読み取れません'];if(!story.meta)e.push('meta がありません');if(!Array.isArray(story.modules)||story.modules.length!==5)e.push('SSTは5場面必要です');if(!Array.isArray(story.transitions)||story.transitions.length!==4)e.push('生活のつなぎは4場面必要です');const ids=new Set();(story.modules||[]).forEach((m,i)=>{if(ids.has(m.id))e.push(`SST${i+1}: idが重複しています`);ids.add(m.id);if(!Array.isArray(m.choices)||m.choices.length!==5)e.push(`SST${i+1}: 主課題は5択必要です`);if(!m.model||!m.model.image)e.push(`SST${i+1}: モデリングがありません`);if(!m.generalize||!Array.isArray(m.generalize.choices)||m.generalize.choices.length<2)e.push(`SST${i+1}: 本編後の確認課題がありません`);if(!Array.isArray(m.repairChoices)||m.repairChoices.length<1)e.push(`SST${i+1}: 修復候補がありません`);const imgs=(m.choices||[]).map(c=>c.image);if(new Set(imgs).size!==imgs.length)e.push(`SST${i+1}: 5択の結果画像が重複しています`)});if(!Array.isArray(story.missions)||story.missions.length<1)e.push('現実ミッションがありません');for(const r of refs(story))if(!files.has(r))e.push(`画像参照がありません: ${r}`);e.push(...walkText(story));return e}
async function digest(data){let b;if(data instanceof ArrayBuffer)b=data;else if(ArrayBuffer.isView(data))b=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength);else b=await data.arrayBuffer();const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function parse(blob,verifyHashes=true){if((blob.size||blob.byteLength||0)>MAX_PACKAGE)throw new Error('ストーリーパックが大きすぎます');const zip=await JSZip.loadAsync(blob);const entries=Object.values(zip.files).filter(x=>!x.dir);if(entries.length>MAX_FILES)throw new Error('ファイル数が多すぎます');let total=0;const fileSet=new Set();for(const ent of entries){const p=cleanPath(ent.name);const ext=p.split('.').pop().toLowerCase();if(!ALLOWED_EXT.has(ext))throw new Error(`許可されていないファイル形式です: ${p}`);fileSet.add(p);const u=ent._data?.uncompressedSize||0;total+=u;if(total>MAX_UNPACKED)throw new Error('展開後の容量が大きすぎます')}if(!zip.file('manifest.json')||!zip.file('story.json'))throw new Error('manifest.json または story.json がありません');const manifest=JSON.parse(await zip.file('manifest.json').async('text'));const story=JSON.parse(await zip.file('story.json').async('text'));if(manifest.format!=='b5-sst-story'||manifest.schemaVersion!=='1.0')throw new Error('B5 SSTストーリーパック形式ではありません');if(!manifest.storyId||!manifest.version)throw new Error('storyId または version がありません');if(story.meta?.storyId!==manifest.storyId)throw new Error('storyId が一致しません');if(story.meta?.version!==manifest.version)throw new Error('version が一致しません');const errors=validateStory(story,fileSet);if(errors.length)throw new Error('ガードレール検査に失敗しました:\n- '+errors.slice(0,12).join('\n- '));if(verifyHashes&&manifest.files){for(const [p,info] of Object.entries(manifest.files)){const zf=zip.file(p);if(!zf)throw new Error(`manifestのファイルがありません: ${p}`);if(info.sha256){const got=await digest(await zf.async('uint8array'));if(got!==info.sha256)throw new Error(`チェックサムが一致しません: ${p}`)}}}return {zip,manifest,story,fileSet}}
async function importBlob(blob,name='story.sststory'){const parsed=await parse(blob);try{await navigator.storage?.persist?.()}catch(_){}const old=await get(parsed.manifest.storyId);await put({storyId:parsed.manifest.storyId,version:parsed.manifest.version,title:parsed.manifest.title,titleRuby:parsed.manifest.titleRuby||parsed.manifest.title,status:parsed.manifest.status||'candidate',size:blob.size,importedAt:new Date().toISOString(),fileName:name,blob});return {manifest:parsed.manifest,replaced:!!old,oldVersion:old?.version||null}}
async function importFile(file){return importBlob(file,file.name)}
async function load(id){const rec=await get(id);if(!rec)throw new Error('ストーリーが見つかりません');const parsed=await parse(rec.blob,false);const urls={};const created=[];for(const p of refs(parsed.story)){const f=parsed.zip.file(p);if(!f)throw new Error(`画像がありません: ${p}`);const blob=await f.async('blob');const url=URL.createObjectURL(blob);urls[p]=url;created.push(url)}const resolved=JSON.parse(JSON.stringify(parsed.story));(function replace(x){if(Array.isArray(x))x.forEach(replace);else if(x&&typeof x==='object')for(const k of Object.keys(x)){const v=x[k];if(typeof v==='string'&&urls[v])x[k]=urls[v];else replace(v)}})(resolved);return {story:resolved,manifest:parsed.manifest,revoke:()=>created.forEach(u=>URL.revokeObjectURL(u))}}
window.B5StoryStore={list,get,remove,parse,importFile,importBlob,load,validateStory};
})();
